name: CI 

on:
  push:
  workflow_dispatch:

jobs:
  rss_validate:
    name: "RSS Validation"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a
        with:
          sparse-checkout: rss.xml
      - name: Run validator
        run: |
          npx feed-validator rss.xml
